# Viser ein "Sponsor"-knapp øvst på repo-sida.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [Hawk-on]
